# Generated by Django 4.2 on 2024-05-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whistle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('useragent', models.TextField()),
                ('viewport_width', models.IntegerField(blank=True, null=True)),
                ('viewport_height', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
