# Generated by Django 4.2 on 2024-05-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_mammoth_whistle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistle',
            name='is_client_event',
            field=models.BooleanField(default=False),
        ),
    ]
