# Generated by Django 5.0.6 on 2024-06-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_mammoth_whistle', '0002_whistle_is_client_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whistle',
            name='viewport_height',
        ),
        migrations.RemoveField(
            model_name='whistle',
            name='viewport_width',
        ),
        migrations.AddField(
            model_name='whistle',
            name='viewport_size',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whistle',
            name='request',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whistle',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='whistle',
            name='useragent',
            field=models.TextField(blank=True),
        ),
    ]
