# Generated by Django 5.0.6 on 2024-06-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_mammoth_whistle', '0004_rename_viewport_size_whistle_viewport_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistle',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
