# Generated by Django 5.1.4 on 2025-02-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silent_mammoth_whistle', '0008_alter_whistle_request_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistle',
            name='referer',
            field=models.TextField(blank=True),
        ),
    ]
